services:
  app:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=exptrack_db
      - POSTGRES_USER=db_admin
      - POSTGRES_PASSWORD=password
    ports:
      - "6543:5432"
    restart: always
