services:
  app:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    command: ["sh", "-c", /expense-tracker-api/bin/migrate up && /expense-tracker-api/bin/api]

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=exptrack_db
      - POSTGRES_USER=db_admin
      - POSTGRES_PASSWORD=password
    ports:
      - "6543:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_admin -d exptrack_db"]
      interval: 3s
      timeout: 5s
      retries: 5
    restart: always
