services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=exptrack_db
      - POSTGRES_USER=db_admin
      - POSTGRES_PASSWORD=password
    ports:
      - "6543:5432"
    restart: always
